version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "shrwnsan"
    assignees:
      - "shrwnsan"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Enable version updates for npm in tests
  - package-ecosystem: "npm"
    directory: "/tests/docker"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "shrwnsan"
    assignees:
      - "shrwnsan"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      test-dev-deps:
        patterns:
          - "prettier"
          - "eslint"
          - "typescript"
          - "rollup"
          - "nodemon"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "shrwnsan"
    assignees:
      - "shrwnsan"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Enable version updates for Docker Compose
  - package-ecosystem: "docker"
    directory: "/tests/docker"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "shrwnsan"
    assignees:
      - "shrwnsan"
    commit-message:
      prefix: "deps"
      include: "scope"